# Generated by Django 5.0 on 2024-02-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LIMIT_BAL', models.FloatField()),
                ('SEX', models.IntegerField()),
                ('EDUCATION', models.FloatField()),
                ('MARRIAGE', models.FloatField()),
                ('AGE', models.FloatField()),
                ('PAY_0', models.FloatField()),
                ('PAY_2', models.FloatField()),
                ('PAY_3', models.FloatField()),
                ('PAY_4', models.FloatField()),
                ('PAY_5', models.FloatField()),
                ('PAY_6', models.FloatField()),
                ('BILL_AMT1', models.FloatField()),
                ('BILL_AMT2', models.FloatField()),
                ('BILL_AMT3', models.FloatField()),
                ('BILL_AMT4', models.FloatField()),
                ('BILL_AMT5', models.FloatField()),
                ('BILL_AMT6', models.FloatField()),
                ('PAY_AMT1', models.FloatField()),
                ('PAY_AMT2', models.FloatField()),
                ('PAY_AMT3', models.FloatField()),
                ('PAY_AMT4', models.FloatField()),
                ('PAY_AMT5', models.FloatField()),
                ('PAY_AMT6', models.FloatField()),
                ('label', models.IntegerField()),
            ],
        ),
    ]
