# Generated by Django 5.0 on 2024-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditscore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_loan', models.CharField(max_length=100)),
                ('payment_behaviour', models.CharField(max_length=100)),
                ('total_emi_per_month', models.FloatField()),
                ('monthly_inhand_salary', models.FloatField()),
                ('num_bank_accounts', models.IntegerField()),
                ('num_credit_cards', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('num_of_loan', models.CharField(max_length=10)),
                ('delay_from_due_date', models.IntegerField()),
                ('num_of_delayed_payment', models.CharField(max_length=10)),
                ('changed_credit_limit', models.CharField(max_length=3)),
                ('num_credit_inquiries', models.FloatField()),
                ('credit_mix', models.FloatField()),
                ('outstanding_debt', models.FloatField()),
                ('credit_utilization_ratio', models.FloatField()),
                ('credit_history_age', models.CharField(max_length=20)),
                ('payment_of_min_amount', models.CharField(max_length=3)),
                ('amount_invested_monthly', models.FloatField()),
            ],
        ),
    ]
